import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import RoundBasicCard from '../components/Card/RoundBasicCard';
import ResponsiveColumns from '../components/FlexGrid/ResponsiveColumns';
import { FeatureItem } from '../models/RecordItem';
import BasicFooter from '../components/Layout/BasicFooter';
const features: FeatureItem[] =
[
  { name: 'style-components', description: 'Test out styled-components support in nextjs, and with theming and props support', linkProp: { href: '/demo/StyledComponentDemo', text: 'demo' } },
  { name: 'responsive design', description: 'Test out responsive design', linkProp: { href: '/demo/ResponsiveDesignDemo', text: 'demo' } },
  { name: 'dot env config',description: 'Dot env can help to support different environment', linkProp: { href: '/demo/DotEnvConfigDemo', text: 'demo' }  },
  { name: 'markdown in next',description: 'Use markdown in nextjs', linkProp: { href: '/demo/MarkDownInNextDemo', text: 'demo' }  },
  { name: 'browser notification',description: 'Test browser notification', linkProp: { href: '/demo/NotificationDemo', text: 'demo' }  },
  { name: 'tsoa swagger',description: 'Provide tsoa openapi swagger ui', linkProp: { href: '/api-doc/', text: 'demo' }  }
];

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <main className={styles.main}>

                <h1 className={styles.title}>
                    Welcome to <a href='#'>Next.js 100 challenge !</a>
                </h1>

                <p className={styles.description}>
                    
                </p>
                <ResponsiveColumns recordItemWidth={600} records={features.map( ({name,...rest},index)=>({title:name,index, showNumber:true,...rest}))} />
            </main>
        </div>
    );
}
