import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import RoundBasicCard from '../components/Card/RoundBasicCard';
import ResponsiveColumns from '../components/FlexGrid/ResponsiveColumns';


const features: { name: string; description: string; linkProp: { href: string; text: string } }[] =
[
  { name: 'style-components', description: 'Test out styled-components support in nextjs, and with theming and props support', linkProp: { href: '/features/StyledComponentHome', text: 'styled-components' } },
  { name: 'Responsive Design', description: 'Test out responsive design', linkProp: { href: '/features/ResponsiveDesign', text: 'responsive design' } }
  
];


// [
//     { name: 'style-components', description: 'Test out styled-components support in nextjs, and with theming and props support', linkProp: { href: '/features/styledComponentHome', text: 'styled-components' } },
//     { name: 'style-components', description: 'Test out styled-components support in nextjs, and with theming and props support', linkProp: { href: '/features/styledComponentHome', text: 'styled-components' } },
//     { name: 'style-components', description: 'Test out styled-components support in nextjs, and with theming and props support', linkProp: { href: '/features/styledComponentHome', text: 'styled-components' } },
//     { name: 'style-components', description: 'Test out styled-components support in nextjs, and with theming and props support', linkProp: { href: '/features/styledComponentHome', text: 'styled-components' } },
//     { name: 'style-components', description: 'Test out styled-components support in nextjs, and with theming and props support', linkProp: { href: '/features/styledComponentHome', text: 'styled-components' } },
//     { name: 'style-components', description: 'Test out styled-components support in nextjs, and with theming and props support', linkProp: { href: '/features/styledComponentHome', text: 'styled-components' } },
//     { name: 'style-components', description: 'Test out styled-components support in nextjs, and with theming and props support', linkProp: { href: '/features/styledComponentHome', text: 'styled-components' } }
// ];



export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name='description' content='Generated by create next app' />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <main className={styles.main}>

                <h1 className={styles.title}>
                    Welcome to <a href='https://nextjs.org'>Next.js 100 chanllagne !</a>
                </h1>

                <p className={styles.description}>
                    
                </p>
                <ResponsiveColumns recordItemWidth={600} records={features.map( ({name,...rest},index)=>({title:name,index, showNumber:true,...rest}))} />
            </main>

            <footer className={styles.footer}>
                <a href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app' target='_blank' rel='noopener noreferrer'>
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    );
}
